name = "Cobblemon Starfall Modpack"
author = "Tastic Productions"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b741b761a2443ac8c5cfdb6d728754078e545f616e9c92d96e9a7738c838a45"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
