name = "Cobblemon Starfall Modpack"
author = "Tastic Productions"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f41641e652256ff353f077af170d3106a4eb17a99589d7a48045a87e35f84fa"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
