name = "Cobblemon Starfall Modpack"
author = "Tastic Productions"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bac3cca21c6b6ab79f4c4707a863eb4f9f8e183e0588afd4ab983e2c1a5c62fb"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
